services:
  redis:
    image: redis:alpine
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - lanyard_net
    volumes:
      - lanyard-redis-data:/data

  lanyard:
    image: ${LANYARD_IMAGE:-lanyard:latest}
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 4001:4001
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_HOST: redis
    networks:
      - lanyard_net

networks:
  lanyard_net:
    driver: overlay

volumes:
  lanyard-redis-data:
    external: true
